config-version: 2

name: 'salesforce_source'
version: '0.0.2'

require-dbt-version: [">=0.18.0", "<0.19.0"]


models:
    salesforce_source:
        materialized: table

vars:
    salesforce_source:
        account: "{{ source('salesforce', 'account') }}" 
        opportunity: "{{ source('salesforce', 'opportunity') }}" 
        user: "{{ source('salesforce', 'user') }}"
        user_role: "{{ source('salesforce', 'user_role') }}"    

        # If there are extra columns you wish to pass through for either
        # the account or opportunity tables you may do so here:
        account_pass_through_columns: []
        opportunity_pass_through_columns: []
        user_pass_through_columns: []
